apiVersion: apps/v1
kind:Deployment
metadata:
  name: nginx-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80